In [1]:
import pickle
import barley_break
import pandas as pd
import numpy as np

In [2]:
first = np.matrix("2, 4, 3; 1, 8, 5; 7, 0, 6")
values = barley_break.get_tree(first)
r, steps, b = values
print(b.directions[1:])
print(len(b.directions) - 1)
print(steps)

[UP, UP, LEFT, DOWN, RIGHT, RIGHT, DOWN]
7
11


In [3]:
barley_break.path_branches

[[[2 4 3]
  [1 8 5]
  [7 0 6]],
 [[2 4 3]
  [1 0 5]
  [7 8 6]],
 [[2 4 3]
  [1 5 0]
  [7 8 6]],
 [[2 4 3]
  [1 5 6]
  [7 8 0]],
 [[2 4 3]
  [1 5 6]
  [7 0 8]],
 [[2 0 3]
  [1 4 5]
  [7 8 6]],
 [[0 2 3]
  [1 4 5]
  [7 8 6]],
 [[1 2 3]
  [0 4 5]
  [7 8 6]],
 [[1 2 3]
  [4 0 5]
  [7 8 6]],
 [[1 2 3]
  [4 5 0]
  [7 8 6]],
 [[1 2 3]
  [4 5 6]
  [7 8 0]]]

[None, UP, UP, LEFT, DOWN, RIGHT, RIGHT, DOWN]